version: "3.8"

services:
  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./reverse-proxy/nginx-default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080
    depends_on:
      - frontend

  frontend:
    build:
      context: ./frontend
    image: komp-registry-frontend:latest
    depends_on:
      backend:
        condition: service_healthy

  backend:
    build:
      context: ./backend
    image: komp-registry-backend:latest
    environment:
      - LISTEN_ADDR=:3001
      - MYSQL_PASSWORD=TopSecret
      - MYSQL_ADDR=mysql:3306
    # Uncomment to bind container to host on port 3001 (for use with curl or if you want to run the frontend from the host machine)
    ports:
    - 3001:3001
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    healthcheck:
      test: "curl localhost:3001/api/komps"
      interval: 1s
      timeout: 1s
      retries: 60

  mysql:
    image: mysql:8.0
    # Uncomment to bind container to host on port 3306 (for use with mysql cli etc)
    # ports:
    # - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=TopSecret
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=komp_registry
    volumes:
      - ./database/mysql-init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    healthcheck:
      test: "mysql --user=root --password=$$MYSQL_ROOT_PASSWORD --host=localhost --port=3306 -e 'select * from komp_registry.Komps'"
      interval: 1s
      timeout: 1s
      retries: 60


